In [1]:
# pip install pandas numpy scikit-learn matplotlib yfinance tensorflow scikeras

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from scikeras.wrappers import KerasRegressor


2024-12-29 16:45:11.457407: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
# Download Apple stock data
data = yf.download("AAPL", start="2015-01-01", end="2023-01-01")

# Calculate moving averages and relative price change
data['SMA_10'] = data['Close'].rolling(window=10).mean()
data['SMA_50'] = data['Close'].rolling(window=50).mean()
data['Price_Change'] = data['Close'].pct_change()

# set target as next days close
data['Target'] = data['Close'].shift(-1)

# Drop rows with missing values
data.dropna(inplace=True)

#print(data.head())

[*********************100%***********************]  1 of 1 completed


In [4]:
#scale data
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X = data[['SMA_10', 'SMA_50', 'Price_Change']]
X_scaled = scaler_X.fit_transform(X)

y = data['Target']
y_scaled = scaler_y.fit_transform(y.to_frame())


# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size=0.2, random_state=42)

print(X_train)
print(f"Training samples: {len(X_train)}, Testing samples: {len(X_test)}")

[[-0.39427465 -0.36631717  0.44833143]
 [ 0.8294438   0.87237632  1.55648348]
 [-0.62213843 -0.65672014 -0.16868121]
 ...
 [-0.46332114 -0.50801801  0.29107062]
 [ 1.14670756  0.97596016 -0.75594717]
 [-0.43484713 -0.43296642  0.84760288]]
Training samples: 1571, Testing samples: 393


In [5]:
#repeatable way to create the model 
def create_ann(neurons=32, activation='relu', optimizer='admin'):
    model = Sequential()
    model.add(Input(shape=(X_train.shape[1],)))  #input structure
    model.add(Dense(neurons, activation=activation)) # hidden layer
    model.add(Dense(neurons, activation=activation)) # hidden layer
    model.add(Dense(1)) #output
    model.compile(loss='mean_squared_error', optimizer=optimizer, metrics=['mae'])
    return model

<h1> GridSearch setup </h1>

In [7]:
# defone model parameters and create model
param_grid = {
    'model__neurons': [16, 32, 64, 128],
    'model__activation': ['relu', 'tanh', 'sigmoid'],
    'model__optimizer': ['adam', 'sgd'],
    'batch_size': [16, 32],
    'epochs': [50, 100, 200]
}

In [8]:
#training
model = KerasRegressor(model=create_ann, verbose=0) #keras regressor is a wrapper to us scikit learn gid search


# Initialize GridSearchCV
grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=3,                       # cross-validation
    scoring='neg_mean_absolute_error',         # Use mse as scoring
    verbose=1,
    n_jobs=-1                   # Use all available cores
)

# Perform grid search on training data
grid_search.fit(X_train, y_train)

results_df = pd.DataFrame(grid_search.cv_results_)


Fitting 3 folds for each of 144 candidates, totalling 432 fits


2024-12-29 16:45:32.527059: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-29 16:45:32.576280: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-29 16:45:32.617983: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-29 16:45:32.715913: I tensorflow/core/platform/cpu_featu

[CV 3/3; 1/144] START batch_size=16, epochs=50, model__activation=relu, model__neurons=16, model__optimizer=adam[CV 1/3; 2/144] START batch_size=16, epochs=50, model__activation=relu, model__neurons=16, model__optimizer=sgd

[CV 1/3; 1/144] START batch_size=16, epochs=50, model__activation=relu, model__neurons=16, model__optimizer=adam
[CV 2/3; 1/144] START batch_size=16, epochs=50, model__activation=relu, model__neurons=16, model__optimizer=adam
[CV 1/3; 2/144] END batch_size=16, epochs=50, model__activation=relu, model__neurons=16, model__optimizer=sgd;, score=-0.049 total time=  22.1s
[CV 2/3; 2/144] START batch_size=16, epochs=50, model__activation=relu, model__neurons=16, model__optimizer=sgd
[CV 1/3; 1/144] END batch_size=16, epochs=50, model__activation=relu, model__neurons=16, model__optimizer=adam;, score=-0.037 total time=  25.7s
[CV 3/3; 2/144] START batch_size=16, epochs=50, model__activation=relu, model__neurons=16, model__optimizer=sgd
[CV 2/3; 1/144] END batch_size=16, e

KeyboardInterrupt: 

In [ ]:
results_df = pd.DataFrame(grid_search.cv_results_).sort_values(by='mean_test_score', ascending=False)
for i, row in results_df.iterrows():
    print(f"Rank {row['rank_test_score']}:")
    print(f"Parameters: {row['params']}")
    print(f"Mean Test Score: {row['mean_test_score']:.4f}")
    print(f"Std Dev of Test Score: {row['std_test_score']:.4f}")
    print("-" * 30)

In [ ]:
# use best model to predict
final_model = grid_search.best_estimator_

# Predict on test data
final_predictions = final_model.predict(X_test)

# Evaluate the final model
mae = mean_absolute_error(y_test, final_predictions)
mse = mean_squared_error(y_test, final_predictions)
rmse = np.sqrt(mse)

print(f"Final Model MAE: {mae}")
print(f"Final Model RMSE: {rmse}")

# Visualize Predictions vs. Actual Outcomes
plt.figure(figsize=(8, 6))
plt.scatter(y_test, final_predictions, alpha=0.7, color='b', label='Predicted vs Actual')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Perfect Prediction')  # Diagonal line
plt.title('Actual vs Predicted Values', fontsize=14)
plt.xlabel('Actual Values', fontsize=12)
plt.ylabel('Predicted Values', fontsize=12)
plt.legend(fontsize=12)
plt.grid(True)
plt.show()

In [ ]:
# trying to predict more recent ones
stock = yf.Ticker('AAPL')
data_to_predict = yf.download("AAPL", start="2024-01-01", end="2024-06-01")
data_to_predict['SMA_10'] = data_to_predict['Close'].rolling(window=10).mean()
data_to_predict['SMA_50'] = data_to_predict['Close'].rolling(window=50).mean()
data_to_predict['Price_Change'] = data_to_predict['Close'].pct_change()
data_to_predict['Target'] = data_to_predict['Close'].shift(-1)
data_to_predict.dropna(inplace=True)

X = data_to_predict[['SMA_10', 'SMA_50', 'Price_Change']]
Y = data_to_predict['Target']

X_scaled = scaler_X.fit_transform(X)
Y_scaled = scaler_y.fit_transform(Y.to_frame())

final_predictions = final_model.predict(X_scaled)

mae = mean_absolute_error(Y_scaled, final_predictions)
mse = mean_squared_error(Y_scaled, final_predictions)
rmse = np.sqrt(mse)

print(f"Final Model MAE: {mae}")
print(f"Final Model RMSE: {rmse}")

# Visualize Predictions vs. Actual Outcomes
plt.figure(figsize=(8, 6))
plt.scatter(Y_scaled, final_predictions, alpha=0.7, color='b', label='Predicted vs Actual')
plt.plot([Y_scaled.min(), Y_scaled.max()], [Y_scaled.min(), Y_scaled.max()], 'r--', lw=2, label='Perfect Prediction')  # Diagonal line
plt.title('Actual vs Predicted Values', fontsize=14)
plt.xlabel('Actual Values', fontsize=12)
plt.ylabel('Predicted Values', fontsize=12)
plt.legend(fontsize=12)
plt.grid(True)
plt.show()